/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package energy_converter;
import static energy_converter.Constants.*;
import java.awt.*;
import java.awt.event.KeyEvent;

public class App {
    String getGreeting()
    {
        return "HelloWorld";
    }
    static Frame frame;
    static boolean loop;
    public static void main(String[] args) {
        frame = new Frame(WIDTH, HEIGHT, "test");
        var FPS = new FPSCheckr();
        var area = new Area();
        var cursel = new Cursel();
        var key = new Keyboard(200);
        var back = new BackGround();
        loop = true;
        var gra = frame.panel.image.getGraphics();
        frame.panel.draw();
        var mode = GameMode.START;
        while(loop)
        {
            FPS.MinTask();
            gra.setColor(Color.WHITE);
            gra.fillRect(0, 0,WIDTH,HEIGHT);

            switch(mode)
            {
                case START:
                    StartMenu(gra);
                    if(key.isKeyPressed(KeyEvent.VK_ENTER))
                    {
                        mode = GameMode.GAME;
                        area.MakeStart();
                    }
                    break;
                case GAME:
                    back.Draw(gra);
                    area.Drop();
                    area.Draw(gra);
                    cursel.Move();
                    cursel.Draw(gra);
                    if(key.isKeyPressed(KeyEvent.VK_ENTER))
                    {
                        area.Swap(cursel.x, cursel.y);
                        key.ResetTimer();
                    }
                    break;
                case GAME_OVER:
                    GameOver(gra);
                    if(key.isKeyPressed(KeyEvent.VK_ENTER))
                        mode = GameMode.START;
            }

            gra.setColor(Color.BLACK);
            gra.setFont(new Font("SansSerif", Font.PLAIN, 10));
            gra.drawString(FPS.FPS+"FPS", 5, HEIGHT-40);

            frame.panel.draw();
            FPS.Sleep();
        }
    }
    static void StartMenu(Graphics gra)
    {
        var Title = "Energy Converter";
        gra.setColor(Color.BLACK);
        gra.setFont(new Font("SansSerif", Font.PLAIN, 40));
        FontMetrics metrics = gra.getFontMetrics();
        gra.drawString(Title, WIDTH/2-metrics.stringWidth(Title)/2,150);
        gra.setColor(Color.BLACK);
        gra.setFont(new Font("SansSerif", Font.PLAIN, 25));
        metrics = gra.getFontMetrics();
        gra.drawString("Pless Enter to Start", WIDTH/2-metrics.stringWidth("Pless Enter to Start")/2,250);
    }
    static void GameOver(Graphics gra)
    {
        gra.setColor(Color.BLACK);
        gra.setFont(new Font("SansSerif", Font.PLAIN, 40));
        FontMetrics metrics = gra.getFontMetrics();
        gra.drawString("GameOver", WIDTH/2-metrics.stringWidth("GameOver")/2,150);
        gra.setColor(Color.BLACK);
        gra.setFont(new Font("SansSerif", Font.PLAIN, 25));
        metrics = gra.getFontMetrics();
        gra.drawString("Pless Enter to Start", WIDTH/2-metrics.stringWidth("Pless Enter to Start")/2,250);
    }
}

